baseurl: https://jarbouvic.github.io
canonifyurls: true

author: Victor Moreau
title: Victor Moreau

languageCode: en-us
contentdir: content
layoutdir: layouts
publishdir: public
pygmentsuseclasses: true
disqusShortname: jarbouvic # Comment out to disable Disqus.
pluralizelisttitles: false
MetaDataFormat: yaml

permalinks:
    fixed: :title/
    blog: blog/:slug/

params:
    Author: "Victor Moreau"
    CacheBuster: true
    DateForm: Jan 2, 2006
    DateFormFull: Mon Jan 2 2006 15:04:05 MST
    Description: Don't panic
    Email: jarbouvic@gmail.com
    FaviconFile: img/leaf.ico
    GATracker: "XYZ"
    GitHub: //github.com/jarbouvic
    HighlightJS: true
    Lang: en
    LinkedIn: //linkedin.com/in/jarbouvic
    Twitter: //twitter.com/jarbouvic
    ExtraCssFiles:
        - /css/override.css

taxonomies:
    tag: "tags"
    category: "categories"

menu:
    main:
        - Name: "Life"
          Identifier: "life"
          URL: "/life/"
        - Name: "Code"
          Identifier: "code"
          URL: "/code/"
...