Baseurl: http://jarbouvic.com
Title: Victor Moreau
LanguageCode: en-us
GoogleAnalytics : UA-12953608-6
DisqusShortname: jarbouvic

Permalinks:
    fixed: :title/
    post: blog/:slug/

params:
    author: Victor Moreau
    email: jarbouvic@gmail.com
    gitHub:
        name: jarbouvic
        url: //github.com/jarbouvic
    linkedIn: 
        name: jarbouvic
        url: //linkedin.com/in/jarbouvic
    twitter:
        name: jarbouvic
        url: //twitter.com/jarbouvic
    description: "Hi! Victor is my name. I live currently in Jakarta, Indonesia. I'm passionate about software. When I'm not changing diapers, I write code."
    keywords: 
        - blog
        - personal
        - software
        - family
        - house-husband
        - development
        - code
        - life
        - website

taxonomies:
    tag: "tags"
    category: "categories"
    language: "language"

Paginate: 5

SectionPagesMenu: "main"
Menu:
    main:
        - Name: "Me"
          Weight: 1
          Identifier: "me"
          URL: "/me/"
        - Name: "Blog"
          Weight: 2
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Work"
          Weight: 3
          Identifier: "work"
          URL: "/work/"

enableRobotsTXT: true
pluralizelisttitles: false
...